/*******************************************************************************
** animate.h (animation timings)
*******************************************************************************/

#ifndef ANIMATE_H
#define ANIMATE_H

/* grid object animations */

/* grid object animations should have a frame length that is a  */
/* multiple of 6, as the grid updates to the vbo every 6 frames */

/* the total length of each animation should divide evenly  */
/* into 240 (if the animation loops longer than 240 frames) */

#define ANIM_WILD_CARD_FRAME_LENGTH   12
#define ANIM_WILD_CARD_NUM_FRAMES     4
#define ANIM_WILD_CARD_TOTAL_LENGTH   (ANIM_WILD_CARD_FRAME_LENGTH * ANIM_WILD_CARD_NUM_FRAMES)

#define ANIM_MARBLE_FLASHING_FRAME_LENGTH   6
#define ANIM_MARBLE_FLASHING_NUM_FRAMES     4
#define ANIM_MARBLE_FLASHING_TOTAL_LENGTH   (ANIM_MARBLE_FLASHING_FRAME_LENGTH * ANIM_MARBLE_FLASHING_NUM_FRAMES)

#define ANIM_MARBLE_CHANGING_FRAME_LENGTH   6
#define ANIM_MARBLE_CHANGING_NUM_FRAMES     6
#define ANIM_MARBLE_CHANGING_TOTAL_LENGTH   (ANIM_MARBLE_CHANGING_FRAME_LENGTH * ANIM_MARBLE_CHANGING_NUM_FRAMES)

#define ANIM_ICE_FRAME_LENGTH     6
#define ANIM_ICE_NUM_FRAMES       40
#define ANIM_ICE_TOTAL_LENGTH     (ANIM_ICE_FRAME_LENGTH * ANIM_ICE_NUM_FRAMES)

#define ANIM_HEART_BLOCK_FRAME_LENGTH   12
#define ANIM_HEART_BLOCK_NUM_FRAMES     2
#define ANIM_HEART_BLOCK_TOTAL_LENGTH   (ANIM_HEART_BLOCK_FRAME_LENGTH * ANIM_HEART_BLOCK_NUM_FRAMES)

#define ANIM_DIAMOND_BLOCK_FRAME_LENGTH 18
#define ANIM_DIAMOND_BLOCK_NUM_FRAMES   2
#define ANIM_DIAMOND_BLOCK_TOTAL_LENGTH (ANIM_DIAMOND_BLOCK_FRAME_LENGTH * ANIM_DIAMOND_BLOCK_NUM_FRAMES)

#define ANIM_MAGI_BLOCK_1_FRAME_LENGTH  6
#define ANIM_MAGI_BLOCK_1_NUM_FRAMES    40
#define ANIM_MAGI_BLOCK_1_TOTAL_LENGTH  (ANIM_MAGI_BLOCK_1_FRAME_LENGTH * ANIM_MAGI_BLOCK_1_NUM_FRAMES)

#define ANIM_MAGI_BLOCK_2_FRAME_LENGTH  6
#define ANIM_MAGI_BLOCK_2_NUM_FRAMES    20
#define ANIM_MAGI_BLOCK_2_TOTAL_LENGTH  (ANIM_MAGI_BLOCK_2_FRAME_LENGTH * ANIM_MAGI_BLOCK_2_NUM_FRAMES)

#define ANIM_FAST_MAGI_BLOCK_1_FRAME_LENGTH   6
#define ANIM_FAST_MAGI_BLOCK_1_NUM_FRAMES     20
#define ANIM_FAST_MAGI_BLOCK_1_TOTAL_LENGTH   (ANIM_FAST_MAGI_BLOCK_1_FRAME_LENGTH * ANIM_FAST_MAGI_BLOCK_1_NUM_FRAMES)

#define ANIM_FAST_MAGI_BLOCK_2_FRAME_LENGTH   6
#define ANIM_FAST_MAGI_BLOCK_2_NUM_FRAMES     10
#define ANIM_FAST_MAGI_BLOCK_2_TOTAL_LENGTH   (ANIM_FAST_MAGI_BLOCK_2_FRAME_LENGTH * ANIM_FAST_MAGI_BLOCK_2_NUM_FRAMES)

#define ANIM_DOOR_OPENING_FRAME_LENGTH  12
#define ANIM_DOOR_OPENING_NUM_FRAMES    4
#define ANIM_DOOR_OPENING_TOTAL_LENGTH  (ANIM_DOOR_OPENING_FRAME_LENGTH * ANIM_DOOR_OPENING_NUM_FRAMES)

#define ANIM_INVIS_APPEARING_FRAME_LENGTH  12
#define ANIM_INVIS_APPEARING_NUM_FRAMES    3
#define ANIM_INVIS_APPEARING_TOTAL_LENGTH  (ANIM_INVIS_APPEARING_FRAME_LENGTH * ANIM_INVIS_APPEARING_NUM_FRAMES)

#define ANIM_BUBBLE_POT_FRAME_LENGTH  6
#define ANIM_BUBBLE_POT_NUM_FRAMES    20
#define ANIM_BUBBLE_POT_TOTAL_LENGTH  (ANIM_BUBBLE_POT_FRAME_LENGTH * ANIM_BUBBLE_POT_NUM_FRAMES)

#define ANIM_ARROWS_FRAME_LENGTH   12
#define ANIM_ARROWS_NUM_FRAMES     4
#define ANIM_ARROWS_TOTAL_LENGTH   (ANIM_ARROWS_FRAME_LENGTH * ANIM_ARROWS_NUM_FRAMES)

/* thing animations */

/* the total length of each animation should divide evenly  */
/* into 240 (if the animation loops longer than 240 frames) */

#define ANIM_BUNNY_WALKING_FRAME_LENGTH   12
#define ANIM_BUNNY_WALKING_NUM_FRAMES     4
#define ANIM_BUNNY_WALKING_TOTAL_LENGTH   (ANIM_BUNNY_WALKING_FRAME_LENGTH * ANIM_BUNNY_WALKING_NUM_FRAMES)

#define ANIM_BUNNY_GRABBING_FRAME_LENGTH  6
#define ANIM_BUNNY_GRABBING_NUM_FRAMES    4
#define ANIM_BUNNY_GRABBING_TOTAL_LENGTH  (ANIM_BUNNY_GRABBING_FRAME_LENGTH * ANIM_BUNNY_GRABBING_NUM_FRAMES)

#define ANIM_BUNNY_THROWING_FRAME_LENGTH  6
#define ANIM_BUNNY_THROWING_NUM_FRAMES    4
#define ANIM_BUNNY_THROWING_TOTAL_LENGTH  (ANIM_BUNNY_THROWING_FRAME_LENGTH * ANIM_BUNNY_THROWING_NUM_FRAMES)

#define ANIM_BUNNY_KICKING_FRAME_LENGTH   6
#define ANIM_BUNNY_KICKING_NUM_FRAMES     4
#define ANIM_BUNNY_KICKING_TOTAL_LENGTH   (ANIM_BUNNY_KICKING_FRAME_LENGTH * ANIM_BUNNY_KICKING_NUM_FRAMES)

#define ANIM_BUNNY_CLIMBING_FRAME_LENGTH  12
#define ANIM_BUNNY_CLIMBING_NUM_FRAMES    4
#define ANIM_BUNNY_CLIMBING_TOTAL_LENGTH  (ANIM_BUNNY_CLIMBING_FRAME_LENGTH * ANIM_BUNNY_CLIMBING_NUM_FRAMES)

#define ANIM_PICKUP_FRAME_LENGTH    10
#define ANIM_PICKUP_NUM_FRAMES      4
#define ANIM_PICKUP_TOTAL_LENGTH    (ANIM_PICKUP_FRAME_LENGTH * ANIM_PICKUP_NUM_FRAMES)

#define ANIM_CRITTER_FRAME_LENGTH   20
#define ANIM_CRITTER_NUM_FRAMES     4
#define ANIM_CRITTER_TOTAL_LENGTH   (ANIM_CRITTER_FRAME_LENGTH * ANIM_CRITTER_NUM_FRAMES)

#define ANIM_CRITTER_HELD_FRAME_LENGTH  10
#define ANIM_CRITTER_HELD_NUM_FRAMES    4
#define ANIM_CRITTER_HELD_TOTAL_LENGTH  (ANIM_CRITTER_HELD_FRAME_LENGTH * ANIM_CRITTER_HELD_NUM_FRAMES)

#define ANIM_KNOB_FAST_FRAME_LENGTH   8
#define ANIM_KNOB_FAST_NUM_FRAMES     3
#define ANIM_KNOB_FAST_TOTAL_LENGTH   (ANIM_KNOB_FAST_FRAME_LENGTH * ANIM_KNOB_FAST_NUM_FRAMES)

#define ANIM_KNOB_SLOW_FRAME_LENGTH   16
#define ANIM_KNOB_SLOW_NUM_FRAMES     3
#define ANIM_KNOB_SLOW_TOTAL_LENGTH   (ANIM_KNOB_SLOW_FRAME_LENGTH * ANIM_KNOB_SLOW_NUM_FRAMES)

#define ANIM_ROCKET_BLOCK_FRAME_LENGTH   15
#define ANIM_ROCKET_BLOCK_NUM_FRAMES     2
#define ANIM_ROCKET_BLOCK_TOTAL_LENGTH   (ANIM_ROCKET_BLOCK_FRAME_LENGTH * ANIM_ROCKET_BLOCK_NUM_FRAMES)

#define ANIM_ELEVATOR_IDLE_FRAME_LENGTH   30
#define ANIM_ELEVATOR_IDLE_NUM_FRAMES     2
#define ANIM_ELEVATOR_IDLE_TOTAL_LENGTH   (ANIM_ELEVATOR_IDLE_FRAME_LENGTH * ANIM_ELEVATOR_IDLE_NUM_FRAMES)

#define ANIM_ELEVATOR_ACTIVE_FRAME_LENGTH   15
#define ANIM_ELEVATOR_ACTIVE_NUM_FRAMES     2
#define ANIM_ELEVATOR_ACTIVE_TOTAL_LENGTH   (ANIM_ELEVATOR_ACTIVE_FRAME_LENGTH * ANIM_ELEVATOR_ACTIVE_NUM_FRAMES)

#define ANIM_BOLT_FAST_FRAME_LENGTH   10
#define ANIM_BOLT_FAST_NUM_FRAMES     4
#define ANIM_BOLT_FAST_TOTAL_LENGTH   (ANIM_BOLT_FAST_FRAME_LENGTH * ANIM_BOLT_FAST_NUM_FRAMES)

#define ANIM_BOLT_SLOW_FRAME_LENGTH   20
#define ANIM_BOLT_SLOW_NUM_FRAMES     4
#define ANIM_BOLT_SLOW_TOTAL_LENGTH   (ANIM_BOLT_SLOW_FRAME_LENGTH * ANIM_BOLT_SLOW_NUM_FRAMES)

#define ANIM_PLATFORM_FRAME_LENGTH  16
#define ANIM_PLATFORM_NUM_FRAMES    3
#define ANIM_PLATFORM_TOTAL_LENGTH  (ANIM_PLATFORM_FRAME_LENGTH * ANIM_PLATFORM_NUM_FRAMES)

#define ANIM_BUBBLE_FLOATING_FRAME_LENGTH   10
#define ANIM_BUBBLE_FLOATING_NUM_FRAMES     4
#define ANIM_BUBBLE_FLOATING_TOTAL_LENGTH   (ANIM_BUBBLE_FLOATING_FRAME_LENGTH * ANIM_BUBBLE_FLOATING_NUM_FRAMES)

#define ANIM_BUBBLE_STRESSED_FRAME_LENGTH   6
#define ANIM_BUBBLE_STRESSED_NUM_FRAMES     5
#define ANIM_BUBBLE_STRESSED_TOTAL_LENGTH   (ANIM_BUBBLE_STRESSED_FRAME_LENGTH * ANIM_BUBBLE_STRESSED_NUM_FRAMES)

/* menu animations */
#define ANIM_MENU_CURSOR_BLINK_FRAME_LENGTH   15
#define ANIM_MENU_CURSOR_BLINK_NUM_FRAMES     2
#define ANIM_MENU_CURSOR_BLINK_TOTAL_LENGTH   (ANIM_MENU_CURSOR_BLINK_FRAME_LENGTH * ANIM_MENU_CURSOR_BLINK_NUM_FRAMES)

#define ANIM_MENU_PAGE_ARROW_FRAME_LENGTH     15
#define ANIM_MENU_PAGE_ARROW_NUM_FRAMES       2
#define ANIM_MENU_PAGE_ARROW_TOTAL_LENGTH     (ANIM_MENU_PAGE_ARROW_FRAME_LENGTH * ANIM_MENU_PAGE_ARROW_NUM_FRAMES)

/* macro for determining current animation frame */
#define ANIM_CURRENT_FRAME(name)                                               \
  ((adjusted_timer_count % ANIM_##name##_TOTAL_LENGTH) / ANIM_##name##_FRAME_LENGTH)

#endif
