/*******************************************************************************
** state.h (states for grid objects and things)
*******************************************************************************/

#ifndef STATE_H
#define STATE_H

enum
{
  STATE_NONE = 0,
  STATE_MARBLE_MATCHED,
  STATE_MARBLE_READY_TO_CHANGE,
  STATE_MARBLE_FLASHING,
  STATE_MARBLE_CHANGING,
  STATE_HEART_BLOCK_FLASHING_TOP,
  STATE_HEART_BLOCK_FLASHING_BOTTOM,
  STATE_DIAMOND_BLOCK_FLASHING_TOP,
  STATE_DIAMOND_BLOCK_FLASHING_BOTTOM,
  STATE_DOOR_BLOCK_READY_TO_OPEN,
  STATE_DOOR_BLOCK_OPENING,
  STATE_INVISIBLE_BLOCK_READY_TO_APPEAR,
  STATE_VISIBLE_BLOCK_APPEARING,
  STATE_CRITTER_TURNING,
  STATE_CRITTER_STUNNED,
  STATE_CRITTER_NEGATE_TURN,
  STATE_ELEVATOR_TURNING,
  STATE_RETRACTING_STOPPED,
  STATE_AWAITING_SNAP_TO_GRID,
  STATE_THROWN_THING_NEGATE_BOUNCE,
  STATE_THROWN_THING_LANDED,
  STATE_THROWN_THING_MAY_HAVE_LANDED,
  STATE_THROWN_MARBLE_EARLY_LANDING
};

#endif
